src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OfferRepository::class)]
class Offer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column(nullable: true)]
    private ?float $salary = null;

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private array $missionList = [];

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private array $profileSearchedList = [];

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $maxApplyDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $deletedAt = null;


    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        if (!$this->createdAt) {
            $this->createdAt = new \DateTime();
        }
    }
    
    #[ORM\ManyToOne(inversedBy: 'offers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    /**
     * @var Collection<int, Application>
     */
    #[ORM\OneToMany(targetEntity: Application::class, mappedBy: 'offer')]
    private Collection $applications;

    /**
     * @var Collection<int, Skill>
     */
    #[ORM\ManyToMany(targetEntity: Skill::class, inversedBy: 'offer')]
    private Collection $skills;

    /**
     * @var Collection<int, Category>
     */
    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'offers')]
    #[ORM\JoinTable(name: 'offer_category')]
    private Collection $categories;

    public function __construct()
    {
        $this->applications = new ArrayCollection();
        $this->skills = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getSalary(): ?float
    {
        return $this->salary;
    }

    public function setSalary(?float $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    /**
     * @return array
     */
    public function getMissionList(): array
    {
        return $this->missionList;
    }

    /**
     * @param array $missionList
     */
    public function setMissionList(array $missionList): self
    {
        $this->missionList = $missionList;

        return $this;
    }

    public function addMission(string $mission): self
    {
        if (!in_array($mission, $this->missionList, true)) {
            $this->missionList[] = $mission;
        }

        return $this;
    }

    public function removeMission(string $mission): self
    {
        $index = array_search($mission, $this->missionList, true);
        if ($index !== false) {
            unset($this->missionList[$index]);
            $this->missionList = array_values($this->missionList); // Réindexer l'array
        }

        return $this;
    }

    /**
     * @return array
     */
    public function getProfileSearchedList(): array
    {
        return $this->profileSearchedList;
    }

    /**
     * @param array $missions
     */
    public function setProfileSearchedList(array $profileSearchedList): self
    {
        $this->profileSearchedList = $profileSearchedList;

        return $this;
    }

    public function addProfileSearched(string $profileSearched): self
    {
        if (!in_array($profileSearched, $this->profileSearchedList, true)) {
            $this->profileSearchedList[] = $profileSearched;
        }

        return $this;
    }

    public function removeProfileSearched(string $profileSearched): self
    {
        $index = array_search($profileSearched, $this->profileSearchedList, true);
        if ($index !== false) {
            unset($this->profileSearchedList[$index]);
            $this->profileSearchedList = array_values($this->profileSearchedList); // Réindexer l'array
        }

        return $this;
    }

    public function getMaxApplyDate(): ?\DateTimeInterface
    {
        return $this->maxApplyDate;
    }

    public function setMaxApplyDate(?\DateTimeInterface $maxApplyDate): self
    {
        $this->maxApplyDate = $maxApplyDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->company ? $this->company->getLocation() : null;
    }
    
    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function getApplicationsCount(): int
    {
        return $this->applications->filter(function ($application) {
            return $application->getDeletedAt() === null;
        })->count();
    }

    public function getActiveApplications(): array
    {
        return $this->applications->filter(function ($application) {
            return $application->getDeletedAt() === null;
        })->toArray();
    }

    public function addApplication(Application $application): static
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setOffer($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): static
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getOffer() === $this) {
                $application->setOffer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Skill>
     */
    public function getSkills(): Collection
    {
        return $this->skills;
    }

    public function addSkill(Skill $skill): static
    {
        if (!$this->skills->contains($skill)) {
            $this->skills->add($skill);
            $skill->addOffer($this);
        }

        return $this;
    }

    public function removeSkill(Skill $skill): static
    {
        if ($this->skills->removeElement($skill)) {
            $skill->removeOffer($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Category>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addOffer($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        if ($this->categories->removeElement($category)) {
            if ($category->getOffers() === $this) {
                $category->addOffer($this);
            }
        }

        return $this;
    }
    
    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }
    
    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;
        return $this;
    }
    
    public function softDelete(): self
    {
        $this->deletedAt = new \DateTimeImmutable();
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name: "user_type", type: "string")]
#[ORM\DiscriminatorMap(["student" => "Student", "company" => "Company", "admin" => "Admin"])]
abstract class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var Collection<int, Notification>
     */
    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'userId')]
    private Collection $notifications;

    /**
     * @var Collection<int, Document>
     */
    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'userId', orphanRemoval: true)]
    private Collection $documents;

    /**
     * @var Collection<int, Message>
     */
    #[ORM\OneToMany(targetEntity: Message::class, mappedBy: 'senderId')]
    private Collection $messages;

    public function __construct()
    {
        $this->notifications = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);

    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): static
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setUserId($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): static
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getUserId() === $this) {
                $notification->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Document>
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): static
    {
        if (!$this->documents->contains($document)) {
            $this->documents->add($document);
            $document->setUserId($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): static
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getUserId() === $this) {
                $document->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSenderId($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getSenderId() === $this) {
                $message->setSenderId(null);
            }
        }

        return $this;
    }

    public function getUserTypeString(): string
    {
        if ($this instanceof Student) {
            return 'Etudiant';
        } elseif ($this instanceof Company) {
            return 'Entreprise';
        } elseif ($this instanceof Admin) {
            return 'Administrateur';
        }

        return 'Inconnu';
    }

    public function getDisplayName(): string
    {
        if ($this instanceof Student) {
            return $this->getFirstName() . ' ' . $this->getLastName();
        } elseif ($this instanceof Company) {
            return $this->getName();
        }
        return 'Administrateur'; 
    }

}

templates/offer/application-detail.html.twig
{% extends 'account/layout.html.twig' %}

{% block accountBody %}
	<div class="container mx-auto p-8 bg-white shadow-md rounded-md">
		<h1 class="text-3xl font-extrabold text-gray-800 mb-8">Détails de la candidature</h1>

		<div class="flex justify-between items-center mb-8">
			<div class="flex items-center space-x-6">
				<div class="w-24 h-24 rounded-full overflow-hidden border border-gray-300">
					<img src="{{ student.profilePicture ? asset('uploads/profile_pictures/' ~ student.profilePicture) : asset('build/images/avatar-default.svg') }}" alt="Photo de profil" class="w-full h-full object-cover">
				</div>
				<div>
					<h2 class="text-2xl font-semibold text-gray-900">{{ student.firstName }}
						{{ student.lastName }}</h2>
					<p class="text-gray-500 mt-1">Genre :
						{{ student.gender|capitalize }}</p>
				</div>
			</div>
			{% if application.deletedAt is not empty %}
			<div class="py-3 px-12 bg-red-600">
				<span class="text-white">Désisté</span>
			</div>
			{% endif %}
		</div>

		<div class="bg-gray-100 p-6 rounded-md mb-6">
			<h3 class="text-xl font-bold text-gray-700 mb-4">Informations personnelles</h3>
			<div class="grid grid-cols-2 gap-4">
				<p>
					<span class="font-semibold">Date de naissance :</span>
					{{ student.dateOfBirth ? student.dateOfBirth|date('d/m/Y') : 'Non spécifiée' }}</p>
				<p>
					<span class="font-semibold">Téléphone :</span>
					{{ student.phone ?: 'Non spécifié' }}</p>
				<p>
					<span class="font-semibold">Ville :</span>
					{{ student.city ?: 'Non spécifiée' }}</p>
				<p>
					<span class="font-semibold">Code postal :</span>
					{{ student.postalCode ?: 'Non spécifié' }}</p>
				<p>
					<span class="font-semibold">Portfolio :</span>
					{% if student.portfolioUrl %}
						<a href="{{ student.portfolioUrl }}" target="_blank" class="text-blue-600 underline">Voir le site</a>
					{% else %}
						Non spécifié
					{% endif %}
				</p>
				<p>
					<span class="font-semibold">Permis de conduire :</span>
					{{ student.isDriver ? 'Oui' : 'Non' }}</p>
				<p>
					<span class="font-semibold">Handicap :</span>
					{{ student.isHandicap ? 'Oui' : 'Non' }}</p>
			</div>
		</div>

		<div class="bg-gray-100 p-6 rounded-md mb-6">
			<h3 class="text-xl font-bold text-gray-700 mb-4">Scolarité</h3>
			<div class="grid grid-cols-2 gap-4">
				<p>
					<span class="font-semibold">Établissement :</span>
					{{ student.studyPlace ?: 'Non spécifié' }}</p>
				<p>
					<span class="font-semibold">Niveau d’éducation :</span>
					{{ student.education ?: 'Non spécifié' }}</p>
			</div>
		</div>

		<div class="bg-gray-100 p-6 rounded-md mb-6">
			<h3 class="text-xl font-bold text-gray-700 mb-4">Compétences</h3>
			{% if student.skills|length > 0 %}
				<ul class="list-disc pl-6 text-gray-700">
					{% for skill in student.skills %}
						<li>{{ skill.name }}</li>
					{% endfor %}
				</ul>
			{% else %}
				<p class="text-gray-500">Aucune compétence spécifiée.</p>
			{% endif %}
		</div>

		<div class="bg-gray-100 p-6 rounded-md mb-6">
			<h3 class="text-xl font-bold text-gray-700 mb-4">Lettre de motivation</h3>
			<div class="bg-white p-6 border border-gray-300 rounded-md text-gray-800">
                <span>{{ application.coverLetter }}</span>
			</div>
		</div>

		<div class="mt-8">
			<a href="{{ path('app_offer_application_list', { id: application.offer.id }) }}" class="inline-block px-6 py-3 bg-blue-600 text-white font-semibold rounded-md shadow-md hover:bg-blue-700">
				Retour à la liste des candidatures
			</a>
		</div>
	</div>
{% endblock %}

templates/offer/application_list.html.twig
{% extends 'account/layout.html.twig' %}

{% block accountBody %}

	<div class="container mx-auto p-8 bg-white shadow-md rounded h-full">
		<h1 class="text-2xl font-bold mb-6">Candidatures pour
			{{ offer.name }}</h1>

		{% if applications|length > 0 %}
			<table class="min-w-full bg-white border border-gray-300 rounded-md">
				<thead>
					<tr>
						<th class="px-4 py-2 border-b font-semibold text-left text-gray-800">Nom du candidat</th>
						<th class="px-4 py-2 border-b font-semibold text-left text-gray-800">Email</th>
						<th class="px-4 py-2 border-b font-semibold text-left text-gray-800">Téléphone</th>
						<th class="px-4 py-2 border-b font-semibold text-left text-gray-800">Date de candidature</th>
						<th class="px-4 py-2 border-b font-semibold text-left text-gray-800">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for application in applications %}
						<tr class="hover:bg-gray-100">
							<td class="px-4 py-2 border-b">{{ application.student.firstName }}
								{{ application.student.lastName }}</td>
							<td class="px-4 py-2 border-b">{{ application.student.email }}</td>
							<td class="px-4 py-2 border-b">{{ application.student.phone }}</td>
							<td class="px-4 py-2 border-b">{{ application.createdAt|date('d/m/Y') }}</td>
							<td class="px-4 py-2 border-b">
								<a href="{{ path('app_application_detail', { id: application.id }) }}" class="text-blue-600 hover:underline">Détails</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="5" class="text-center py-4 text-gray-500">Aucune candidature trouvée.</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% else %}

			<p class="text-gray-500">Il n'y a actuellement aucune candidature pour cette offre.</p>
		{% endif %}
        <div class="mt-8">
            <a href="{{ path('app_company_offer_list')}}" class="inline-block px-6 py-3 bg-blue-600 text-white font-semibold rounded-md shadow-md hover:bg-blue-700">
                Retour à la liste des offres
            </a>
        </div>

	</div>

{% endblock %}

templates/offer/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="flex flex-col bg-gray-200">
		<div class="container mx-auto my-13">
			<div class="p-6 border border-gray-300 bg-white">
				<div class="flex justify-between items-center">
					<div class="flex items-center">
						<img alt="" src="{{ asset('build/images/uploads/company/' ~ offer.company.logo) }}" class="w-16 h-16 object-contain">
						<div class="ms-6">
							<h1 class="mb-2 font-semibold text-xl">{{ offer.name }}</h1>
							<p class="mb-2 text-lg">
								<span class="font-bold">{{ offer.company.name }}</span>
								•
								{{ offer.company.location }}
								• Du
								{{ offer.startDate|date('d/m/Y') }}
								au
								{{ offer.endDate|date('d/m/Y') }}
								• ({{ offer.duration }}
								jours)
							</p>
							<div class="flex items-center pt-2">
								<div class="pr-2">
									<span class="px-4 py-2 bg-[#f8f8fd] rounded-xl text-blue-dark text-blue-700 capitalize">{{ offer.type }}</span>
								</div>
								<div class="flex justify-start items-center flex-wrap gap-2 ml-2">
									{% for category in offer.categories %}
										<span class="px-2 py-1 rounded-lg text-sm font-medium" style="background-color:
																																																																																																												{{ category.color|hex_to_rgba(0.2)}}; color:
																																																																																																												{{ category.color }};">
											{{ category.name }}
										</span>
									{% endfor %}
								</div>
							</div>
						</div>
					</div>

					{% if app.user is not null and app.user.userTypeString is same as 'Etudiant' %}
						<div class="flex gap-x-8">
							{% if hasApplied %}
								<div class="text-green-600 font-bold">
									Vous avez déjà postulé à cette offre.
								</div>
							{% else %}
							<div class="flex items-center text-white font-bold bg-blue-600 hover:bg-blue-700 transition">
								<a href="{{ path('app_offer_apply', { id: offer.id, type: offer.type }) }}" class="px-14 py-4">Postuler</a>
							</div>
							{% endif %}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<div class="mt-14 pb-18 border-b container mx-auto flex ">
		<div class="w-2/3 mr-16">
			<div class="mb-10">
				{% if offer.type is same as('stage') %}
					<h2 class="font-semibold mb-4 text-[32px] text-grey-dark">A propos de ce stage</h2>
				{% else %}
					<h2 class="font-semibold mb-4 text-[32px] text-grey-dark">A propos de cette alternance</h2>
				{% endif %}
				<p>{{offer.description}}</p>
			</div>

			<div class="mb-10">
				<h2 class="font-semibold mb-4 text-[32px] text-grey-dark">Missions</h2>
				<ul class="list-img-check">
					{% for mission in offer.missionList %}
						<li class="ms-8">{{ mission }}</li>
					{% else %}
						<li class="ms-8">Aucune mission définie</li>
					{% endfor %}
				</ul>
			</div>

			<div class="mb-10">
				<h2 class="font-semibold mb-4 text-[32px] text-grey-dark">Profil recherché</h2>
				<ul class="list-img-check">
					{% for profileSearched in offer.profileSearchedList %}
						<li class="ms-8">{{ profileSearched }}</li>
					{% else %}
						<li class="ms-8">Aucun profil recherché défini</li>
					{% endfor %}
				</ul>
			</div>

			{% if hasApplied %}
				<div class="text-green-600 font-bold">
					Vous avez déjà postulé à cette offre.
				</div>
			{% else %}
				{% if app.user is not null and app.user.userTypeString is same as 'Etudiant' %}
					<div class="flex gap-x-8">
						<div class="flex items-center text-white font-bold bg-blue-600 hover:bg-blue-700 transition">
							<a href="{{ path('app_offer_apply', { id: offer.id, type: offer.type }) }}" class="px-14 py-4">Postuler</a>
						</div>
					</div>
				{% endif %}
			{% endif %}



		</div>
		<div class="w-1/3">
			<div class="pb-10">
				<div class="flex flex-col gap-y-6 justify-between">
					<div class="flex justify-between">
						<span>Type d’offre</span>
						<span class="font-semibold capitalize text-blue-dark">{{offer.type}}</span>
					</div>
					<div class="flex justify-between">
						<span>Postulet avant le
						</span>
						<span class="font-semibold capitalize text-blue-dark">{{offer.maxApplyDate|date('d/m/Y')}}</span>

					</div>
					<div class="flex justify-between">
						<span>Offre publiée le</span>
						<span class="font-semibold capitalize text-blue-dark">{{offer.createdAt|date('d/m/Y')}}</span>
					</div>
					<div class="flex justify-between">
						<span>Gratification</span>
						{% if offer.type is same as('stage') %}
							{% if offer.salary is not empty %}
								<span class="font-semibold text-blue-dark">{{offer.salary}}€/mois</span>
							{% elseif offer.duration > 44 %}
								<span class="font-semibold text-blue-dark">Obligatoire</span>
							{% else %}
								<span class="font-semibold text-blue-dark">Non obligatoire</span>
							{% endif %}
						{% elseif offer.salary is not empty %}
							<span class="font-semibold text-blue-dark">{{offer.salary}}€/mois</span>
						{% else %}
							<span class="font-semibold text-blue-dark">Non renseigné</span>
						{% endif %}
					</div>
					<div class="flex justify-between">
						<span>Candidatures déposées</span>
						<span class="font-semibold text-blue-dark">{{applicationsCount}}</span>
					</div>
					{% if hasApplied %}
						<div class="text-green-600 font-bold">
							Vous avez déjà postulé à cette offre.
						</div>
					{% endif %}
				</div>
			</div>

			<div class="py-10 border-t">
				<h2 class="text-blue-dark text-2xl font-semibold mb-6">Profils métiers</h2>
				{% if offer.categories is defined %}
					<div class="flex justify-start items-center flex-wrap gap-2 ms-2">
						{% for category in offer.categories %}
							<span class="px-2 py-1 rounded-lg text-sm font-medium" style="background-color:
																																																																																								{{ category.color|hex_to_rgba(0.2)}}; color:
																																																																																								{{ category.color }};">
								{{ category.name }}
							</span>
						{% else %}
							<span class="ps-4">Non renseigné</span>
						{% endfor %}
					</div>
				{% else %}
					<span class="ps-4">Non renseigné</span>
				{% endif %}
			</div>

			<div class="py-10 border-t">
				<h2 class="text-blue-dark text-2xl font-semibold mb-6">Compétences recherchées</h2>
				{% if offer.skills is defined %}
					<div class="flex flex-wrap justify-start gap-2 ms-2">
						{% for skill in offer.skills %}
							<span class="px-2 py-1 rounded-lg text-sm font-medium bg-blue-100 text-blue-700">{{ skill.name }}</span>


						{% else %}
							<span class="ps-4">Non renseigné</span>
						{% endfor %}
					</div>
				{% else %}
					<span class="ps-4">Non renseigné</span>
				{% endif %}
			</div>
		</div>
	</div>

	<div class="mt-18 container mx-auto">
		<a href="{{ path('app_company_detail', {id: offer.company.id})}}" class="flex flex-row items-center gap-x-8 mb-8">
			<img alt={{offer.company.name}} src="{{ asset('build/images/uploads/company/' ~ offer.company.logo) }}" class="max-w-20"></img>
			<span class="text-2xl font-bold">{{offer.company.name}}</span>
		</a>
		<p class="mb-8">
			{{offer.company.description}}
		</p>
		<a href="{{ path('app_company_detail', {id: offer.company.id})}}">
			En savoir plus sur {{offer.company.name}}
		</a>
	</div>

<div class="mt-16 pb-20 pt-18 last-request-container">
	<div class="container mx-auto">
		<div class="flex flex-row justify-between items-center">
			{% if offer.type is same as('stage') %}
				<h2 class="text-xl font-semibold text-grey-dark">Offres de stage similaires</h2>
			{% else %}
				<h2 class="text-xl font-semibold text-grey-dark">Offres d'alternance similaires</h2>
			{% endif %}
			<a href="{{ path(routeListName)}}" class="text-blue-700">Toutes les offres</a>
		</div>
		<div class="mt-12 mb-18 offer-container">
		
			{% for similarOffer in similarOffers %}
				<a href="{{ path('app_offer_detail', {id: similarOffer.id, type:similarOffer.type})}}" class="bg-white offer-card border h-[283px] overflow-hidden justify-between flex flex-col">
					<div class="flex justify-between items-start">
						<img alt={{similarOffer.company.name}} src="{{ asset('build/images/uploads/company/' ~ similarOffer.company.logo) }}" class="object-contain w-12 h-12"></img>
					<span class="px-4 py-2 bg-[#f8f8fd] rounded-xl text-blue-dark text-blue-700 capitalize">{{similarOffer.type}}</span>
				</div>

				<div class="my-2">
					<h3 class="font-semibold text-[18px]">{{similarOffer.name}}</h3>
					<p class="offer-informations text-md text-wrap">{{similarOffer.company.name}}
						•
						{{similarOffer.location}}</p>
				</div>
				<p class="opacity-50 text-md relative txt-elipsis line-clamp-3">{{similarOffer.description}}</p>

				{% if similarOffer.categories is defined and similarOffer.categories|length > 0 %}
					<div class="flex justify-start items-center flex-wrap gap-2">
						{% for category in similarOffer.categories|slice(0, 2) %}
							<span class="px-2 py-1 rounded-lg text-sm font-medium" style="background-color: {{ category.color|hex_to_rgba(0.2) }}; color: {{ category.color }};">
								{{ category.name }}
							</span>
						{% endfor %}

						{% if similarOffer.categories|length > 2 %}
							<span class="px-2 py-1 rounded-lg text-sm font-medium bg-gray-200 text-gray-800">
								+{{ similarOffer.categories|length - 2 }}
							</span>
						{% endif %}
					</div>
				{% endif %}

			</a>
		{% endfor %}
	</div>
</div></div>{% endblock %}